name: Create and release package

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install -U jupyterlab~=3.2.8 setuptools twine build

      - name: Build package
        run: |
          python -m build

      - name: Release on Pypi
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USER }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASS }}
        run: |
          echo "Publishing on pypi..."
          twine upload dist/*
